### ISSUE TITLE
How precise on browser side?

### ISSUE THREAD

**Issue by binarykitchen** [theroyalwhee0/hrdate#11]
Yo!

Curious how precisely your magic records timestamps on browser side?

Couldn't find that answer in your docu. Thanks.

**Comment by theroyalwhee0** [comment]
Whoa, sorry. I must have missed the GitHub notification for this issue. Little late for a response I'm sure, but... The library only works in node. It doesn't work in the browser. I had considered updating it to work in the browser, but I never had a need for it. #12
